name: Genums Client Library

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main]
      
jobs:
  lint:
    name: Lint and Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Clone
      - name: Checkout code
        uses: actions/checkout@v4

      # Install environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      # Install golanci-lint
      - name: Install golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint --version


      - name: Searching for vulnerabilities
        run: make lint

      - name: Executing tests
        run: make test
        
